add some guardrails to the restart command
Co-authored-by: Peba <peba@fastly.com>

diff --git a/bin/restart b/bin/restart
--- a/bin/restart
+++ b/bin/restart
@@ -1,9 +1,37 @@
 #!/bin/bash
 
-if [[ ! -e 'docker-compose.yml' ]]; then
-  echo "Please make sure you are in a specific chapter directory with a docker compose file."
+export colima_exists=false
+
+if which colima >/dev/null 2>&1; then
+    colima_exists=true
+fi
+
+if [[ "$colima_exists" == false && $(which docker-desktop) == "docker-desktop not found" ]]; then
+  echo "You need a docker management software installed. Please read Chapter 000-getting-started to install Colima."
   exit 1
 fi
+
+if [[ "$colima_exists" == "true" ]]; then
+  # check to see if colima is running
+  # Capture the exit code
+  colima status 
+  export exit_code=$?
+
+  echo $exit_code
+
+  # Check the exit code
+  if [ $exit_code -ne 0 ]; then
+      echo "Colima does not appear to be running. Try running "colima start" and then run this command again."
+      exit 1
+  fi
+
+  if [[ ! -e 'docker-compose.yml' ]]; then
+    echo "Please make sure you are in a specific chapter directory with a docker compose file."
+    exit 1
+  fi
+fi
+
+
 
 docker compose down
 
